version: '3'

services:

  realworlddb:
    image: postgres:10.1-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5400:5432

  realworldapp:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: realworldapp
    depends_on:
      - realworlddb
    volumes:
      - ..:/app
    env_file:
      - ../.env
    ports:
      - "8000:80"
    command: /start